INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (1, '謝麗欣', 'OneShotahGwxLJNqzmPWu', '沃尔玛', 22);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (2, 'Edwin Morgan', 'OneShotSOSqLemjGrBvhs', '男', 58);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (4, 'Karen Ross', 'OneShotjZZsrYymisAFva', '女', 42);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (5, '王慧敏', 'OneShotTPtEOiOTDJdUsH', '男', 50);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (6, '严云熙', 'OneShotfsIIkGuRYLGrne', '女', 23);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (7, 'Jeffrey Roberts', 'OneShotqnXyxuEnHeyEds', '未知', 37);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (8, '杜子韬', 'OneShotpBEJQxLZoArnrO', '女', 25);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (9, '黃學友', 'OneShotySBENiBJFORYbw', '女', 52);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (10, 'Leslie Daniels', 'OneShotsceuwRqxaREUTS', '女', 43);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (11, '池田葉月', 'OneShotNceORjUwMRkRem', '女', 50);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (12, '方璐', 'OneShotwGPrMqBDfgVYeJ', '男', 51);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (13, '吉田陽太', 'OneShotqURVHsaJAdiXUq', '未知', 58);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (14, 'Jessica Owens', 'OneShotrSdXIcOsoSqnxN', '未知', 52);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (15, '原涼太', 'OneShotxQuurIyXPwviTD', '男', 31);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (16, '高明詩', 'OneShotnEFgzgXXNSDBGG', '女', 32);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (17, '江詩涵', 'OneShotaISauTwXyBtwhO', '未知', 42);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (18, '赵子异', 'OneShotOcNEHNViRHTMqv', '女', 24);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (19, '増田健太', 'OneShotkqLIdrflbNxSCv', '女', 39);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (20, 'Kevin Williams', 'OneShotEAHAcRhofvPPFH', '男', 59);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (21, '魏安琪', 'OneShotteEXABsNRDeDDv', '未知', 22);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (22, '王曉彤', 'OneShotiozlvZJewbMbNG', '未知', 42);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (23, 'Patricia Nguyen', 'OneShottTAkiesTUJgzmk', '沃尔玛', 36);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (24, '邵天榮', 'OneShotNkFasLXorRUikI', '沃尔玛', 41);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (26, 'Lewis', 'OneShotismylife', '男', 19);
