INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (1, '謝麗欣', 'OneShotahGwxLJNqzmPWu', 'male', 22);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (2, 'Edwin Morgan', 'OneShotSOSqLemjGrBvhs', 'male', 58);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (4, 'Karen Ross', 'OneShotjZZsrYymisAFva', 'female', 42);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (5, '王慧敏', 'OneShotTPtEOiOTDJdUsH', 'male', 50);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (6, '严云熙', 'OneShotfsIIkGuRYLGrne', 'female', 23);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (7, 'Jeffrey Roberts', 'OneShotqnXyxuEnHeyEds', 'male', 37);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (8, '杜子韬', 'OneShotpBEJQxLZoArnrO', 'female', 25);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (9, '黃學友', 'OneShotySBENiBJFORYbw', 'female', 52);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (10, 'Leslie Daniels', 'OneShotsceuwRqxaREUTS', 'female', 43);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (11, '池田葉月', 'OneShotNceORjUwMRkRem', 'female', 50);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (12, '方璐', 'OneShotwGPrMqBDfgVYeJ', 'male', 51);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (13, '吉田陽太', 'OneShotqURVHsaJAdiXUq', 'male', 58);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (14, 'Jessica Owens', 'OneShotrSdXIcOsoSqnxN', 'male', 52);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (15, '原涼太', 'OneShotxQuurIyXPwviTD', 'male', 31);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (16, '高明詩', 'OneShotnEFgzgXXNSDBGG', 'female', 32);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (17, '江詩涵', 'OneShotaISauTwXyBtwhO', 'female', 42);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (18, '赵子异', 'OneShotOcNEHNViRHTMqv', 'female', 24);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (19, '増田健太', 'OneShotkqLIdrflbNxSCv', 'female', 39);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (20, 'Kevin Williams', 'OneShotEAHAcRhofvPPFH', 'male', 59);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (21, '魏安琪', 'OneShotteEXABsNRDeDDv', 'female', 22);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (22, '王曉彤', 'OneShotiozlvZJewbMbNG', 'female', 42);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (23, 'Patricia Nguyen', 'OneShottTAkiesTUJgzmk', 'walmart', 36);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (24, '邵天榮', 'OneShotNkFasLXorRUikI', 'walmart', 41);
INSERT INTO `user` (`id`, `user_name`, `personal_signature`, `gender`, `age`) VALUES (26, 'Lewis', 'OneShotismylife', 'male', 19);
