
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OneShot
    username: OneShot
    password: OneShot

mybatis:
#  mapper-locations: classpath:mapper/*.xml
  #???????resultType?????
  type-aliases-package: com.ShengQin.OneShot.Entities
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

