
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oneshot1
    username: root
    password: root
  mail:
    host: smtp.163.com
    port: 25
    username: 13907587111@163.com
    password: Yinliqi168
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 9090


